apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-west-2

nodeGroups:
  - name: Test
    instanceType: t2.small
    desiredCapacity: 10
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 2
