apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonekartik
  labels:
    app: capstonekramesh
spec:
  selector:
    matchLabels:
      app: capstonekartik
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 1200
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: capstonekartik
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - capstonekartik
              - key: "temporary"
                operator: In
                values:
                - "true"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: udacity
        image: kramiyer/capstonekramesh
        command: [
          "python",
          "web.py"
          ]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
            cpu: 250m
          requests:
            memory: 32Mi
            cpu: 200m
        ports:
          - containerPort: 9080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 9080
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: capstonekartik
spec:
  type: LoadBalancer
  selector:
    app: capstonekartik
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080

      
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: capstonekartik
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: capstonekartik
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

